In [1]:
import math
from collections import Counter

def calculate_statistics(numbers):
    n = len(numbers)

    # Mean
    mean = sum(numbers) / n

    # Median
    sorted_numbers = sorted(numbers)
    if n % 2 == 0:
        median = (sorted_numbers[n//2 - 1] + sorted_numbers[n//2]) / 2
    else:
        median = sorted_numbers[n//2]

    # Mode
    frequency = Counter(numbers)
    mode = max(frequency, key=frequency.get)

    # Variance
    variance = sum((x - mean) ** 2 for x in numbers) / (n - 1)

    # Standard Deviation
    std_deviation = math.sqrt(variance)

    return mean, median, mode, variance, std_deviation


numbers = [10, 20, 20, 30, 40, 50]

mean, median, mode, variance, std_deviation = calculate_statistics(numbers)

print("Numbers:", numbers)
print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Numbers: [10, 20, 20, 30, 40, 50]
Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666669
Standard Deviation: 14.719601443879746


In [2]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:")
print(arr)

# 1. Find sum and mean
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))

# 2. Find maximum and minimum
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# 3. Reshape the array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped Array (2x3):")
print(reshaped_arr)

# 4. Element-wise multiplication
# Multiply each element by 2
multiplied_arr = arr * 2
print("\nElement-wise Multiplication (array * 2):")
print(multiplied_arr)

Original Array:
[10 20 30 40 50 60]

Sum: 210
Mean: 35.0
Maximum: 60
Minimum: 10

Reshaped Array (2x3):
[[10 20 30]
 [40 50 60]]

Element-wise Multiplication (array * 2):
[ 20  40  60  80 100 120]


In [3]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

# Addition
addition = matrix1 + matrix2
print("\nAddition:")
print(addition)

# Subtraction
subtraction = matrix1 - matrix2
print("\nSubtraction:")
print(subtraction)

# Matrix Multiplication
# For multiplication, adjust dimensions
matrix3 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

multiplication = np.dot(matrix1, matrix3)
print("\nMatrix Multiplication (matrix1 × matrix3):")
print(multiplication)

# Transpose of matrix1
transpose = matrix1.T
print("\nTranspose of Matrix 1:")
print(transpose)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Addition:
[[ 8 10 12]
 [14 16 18]]

Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Matrix Multiplication (matrix1 × matrix3):
[[22 28]
 [49 64]]

Transpose of Matrix 1:
[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np

# Generate a random array of 10 numbers (between 0 and 100)
arr = np.random.randint(0, 100, 10)

print("Random Array:")
print(arr)

# Calculate Mean
mean = np.mean(arr)

# Calculate Standard Deviation
std_dev = np.std(arr)

# Find Minimum and Maximum
minimum = np.min(arr)
maximum = np.max(arr)

print("\nMean:", mean)
print("Standard Deviation:", std_dev)
print("Minimum Value:", minimum)
print("Maximum Value:", maximum)

Random Array:
[36 13 16 68 46 34 35 30 15 19]

Mean: 31.2
Standard Deviation: 16.104657711357916
Minimum Value: 13
Maximum Value: 68


In [5]:
import numpy as np
from scipy import stats

# Sample dataset
data = np.array([12, 15, 14, 10, 13, 18, 20, 17, 16, 14])

# 1. Calculate Mean using scipy.stats
mean = stats.tmean(data)

print("Sample Data:", data)
print("Mean (using scipy.stats):", mean)

# 2. Perform One-Sample t-test
# Test if the sample mean is significantly different from 15
t_statistic, p_value = stats.ttest_1samp(data, 15)

print("\nOne-Sample t-Test (H0: mean = 15)")
print("t-statistic:", t_statistic)
print("p-value:", p_value)

# Interpretation
if p_value < 0.05:
    print("Result: Reject the null hypothesis (significant difference).")
else:
    print("Result: Fail to reject the null hypothesis (no significant difference).")

Sample Data: [12 15 14 10 13 18 20 17 16 14]
Mean (using scipy.stats): 14.9

One-Sample t-Test (H0: mean = 15)
t-statistic: -0.10680282817633528
p-value: 0.9172882375665643
Result: Fail to reject the null hypothesis (no significant difference).


In [6]:
import numpy as np
from scipy import integrate

# Define the mathematical function
def f(x):
    return x**2 + 3*x + 2

# Compute definite integral from a to b
a = 0   # Lower limit
b = 5   # Upper limit

result, error = integrate.quad(f, a, b)

print("Definite Integration of f(x) = x^2 + 3x + 2")
print("Limits: ", a, "to", b)
print("Integral Result:", result)
print("Estimated Error:", error)

Definite Integration of f(x) = x^2 + 3x + 2
Limits:  0 to 5
Integral Result: 89.16666666666669
Estimated Error: 9.89948863624098e-13


In [7]:
import numpy as np
from scipy import optimize

# Define the function to minimize
# Example: f(x) = x^2 + 4x + 4
def f(x):
    return x**2 + 4*x + 4

# Initial guess
initial_guess = 0

# Perform minimization
result = optimize.minimize(f, initial_guess)

# Display results
print("Function: f(x) = x^2 + 4x + 4")
print("Minimum value found at x =", result.x[0])
print("Minimum function value =", result.fun)
print("Success:", result.success)
print("Message:", result.message)

Function: f(x) = x^2 + 4x + 4
Minimum value found at x = -2.00000001888464
Minimum function value = 0.0
Success: True
Message: Optimization terminated successfully.
